from tkinter import*
root=Tk()
root.title("notepad")
root.geometry("766x566")
def hello():
    print("hello")

# mainmenu=Menu(root)
# mainmenu.add_command(label="file",command=hello)
# mainmenu.add_command(label="save",command=hello)
# root.config(menu=mainmenu)

mainmenu=Menu(root)
m1=Menu(mainmenu,tearoff=0)
m1.add_command(label="file",command=hello)
m1.add_command(label="save",command=hello)
m1.add_command(label="save as",command=hello)
m1.add_separator()
m1.add_command(label="new",command=hello)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="File",menu=m1)

m2=Menu(mainmenu,tearoff=0)
m2.add_command(label="cut",command=hello)
m2.add_command(label="copy",command=hello)
m2.add_command(label="paste",command=hello)
m2.add_separator()
m2.add_command(label="bold",command=hello)
m2.add_command(label="paste",command=hello)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="Font",menu=m2)
root.mainloop()